export const FORM_NEW_PROJECT = 'FORM_NEW_PROJECT';
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const VALIDATE_FORM_NEW_PROJECT = 'VALIDATE_FORM_NEW_PROJECT';
export const GET_ACTUAL_PROJECT = 'GET_ACTUAL_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const TASK_PROJECT = 'TASK_PROJECT';
export const ADD_TASK = 'ADD_TASK';
export const VALIDATE_TASK = 'VALIDATE_TASK';
