export const FORM_NEW_PROJECT = 'FORM_NEW_PROJECT';
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const VALIDATE_FORM_NEW_PROJECT = 'VALIDATE_FORM_NEW_PROJECT';
export const GET_ACTUAL_PROJECT = 'GET_ACTUAL_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const PROJECT_ERROR = 'PROJECT_ERROR'

export const TASK_PROJECT = 'TASK_PROJECT';
export const ADD_TASK = 'ADD_TASK';
export const VALIDATE_TASK = 'VALIDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const STATUS_TASK = 'STATUS_TASK';
export const ACTUAL_TASK = 'ACTUAL_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const SUCESSFULL_REGISTER = 'SUCESSFULL_REGISTER';
export const ERROR_REGISTER = 'ERROR_REGISTER';
export const GET_USER = 'GET_USER';
export const SUCCESSFULL_LOGIN = 'SUCCESSFULL_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const LOGOUT = 'LOGOUT';